/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-permissions': RouteRecordInfo<
      'settings-permissions',
      '/settings/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-permissions-detail': RouteRecordInfo<
      'settings-permissions-detail',
      '/settings/permissions/:permissionId/detail',
      { permissionId: ParamValue<true> },
      { permissionId: ParamValue<false> },
      | never
    >,
    'settings-roles': RouteRecordInfo<
      'settings-roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-roles-detail': RouteRecordInfo<
      'settings-roles-detail',
      '/settings/roles/:roleId/detail',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | 'settings-roles-detail-permissions'
    >,
    'settings-roles-detail-permissions': RouteRecordInfo<
      'settings-roles-detail-permissions',
      '/settings/roles/:roleId/detail/permissions',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-edit': RouteRecordInfo<
      'settings-roles-edit',
      '/settings/roles/:roleId/edit',
      { roleId: ParamValue<true> },
      { roleId: ParamValue<false> },
      | never
    >,
    'settings-roles-create': RouteRecordInfo<
      'settings-roles-create',
      '/settings/roles/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users': RouteRecordInfo<
      'settings-users',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings-users-detail': RouteRecordInfo<
      'settings-users-detail',
      '/settings/users/:userId/detail',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | 'settings-users-detail-role-assignments'
    >,
    'settings-users-detail-role-assignments': RouteRecordInfo<
      'settings-users-detail-role-assignments',
      '/settings/users/:userId/detail/role-assignments',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-edit': RouteRecordInfo<
      'settings-users-edit',
      '/settings/users/:userId/edit',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    'settings-users-create': RouteRecordInfo<
      'settings-users-create',
      '/settings/users/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors': RouteRecordInfo<
      'vendors',
      '/vendors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-detail': RouteRecordInfo<
      'vendors-detail',
      '/vendors/:vendorId/detail',
      { vendorId: ParamValue<true> },
      { vendorId: ParamValue<false> },
      | 'vendors-detail-bim'
      | 'vendors-detail-contacts'
      | 'vendors-detail-documents'
      | 'vendors-detail-reviews'
    >,
    'vendors-detail-bim': RouteRecordInfo<
      'vendors-detail-bim',
      '/vendors/:vendorId/detail/bim',
      { vendorId: ParamValue<true> },
      { vendorId: ParamValue<false> },
      | never
    >,
    'vendors-detail-contacts': RouteRecordInfo<
      'vendors-detail-contacts',
      '/vendors/:vendorId/detail/contacts',
      { vendorId: ParamValue<true> },
      { vendorId: ParamValue<false> },
      | never
    >,
    'vendors-detail-documents': RouteRecordInfo<
      'vendors-detail-documents',
      '/vendors/:vendorId/detail/documents',
      { vendorId: ParamValue<true> },
      { vendorId: ParamValue<false> },
      | never
    >,
    'vendors-detail-reviews': RouteRecordInfo<
      'vendors-detail-reviews',
      '/vendors/:vendorId/detail/reviews',
      { vendorId: ParamValue<true> },
      { vendorId: ParamValue<false> },
      | never
    >,
    'vendors-mine': RouteRecordInfo<
      'vendors-mine',
      '/vendors/mine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-bidang-usaha': RouteRecordInfo<
      'vendors-mine-bidang-usaha',
      '/vendors/mine/bidang-usaha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-contact-person': RouteRecordInfo<
      'vendors-mine-contact-person',
      '/vendors/mine/contact-person',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-data-pendukung-keuangan': RouteRecordInfo<
      'vendors-mine-data-pendukung-keuangan',
      '/vendors/mine/data-pendukung-keuangan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-data-pendukung-legal': RouteRecordInfo<
      'vendors-mine-data-pendukung-legal',
      '/vendors/mine/data-pendukung-legal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-data-pendukung-teknis': RouteRecordInfo<
      'vendors-mine-data-pendukung-teknis',
      '/vendors/mine/data-pendukung-teknis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-input-bim': RouteRecordInfo<
      'vendors-mine-input-bim',
      '/vendors/mine/input-bim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-mine-konfirmasi-selesai': RouteRecordInfo<
      'vendors-mine-konfirmasi-selesai',
      '/vendors/mine/konfirmasi-selesai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'auth-login': RouteRecordInfo<
      'auth-login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-register': RouteRecordInfo<
      'vendors-register',
      '/vendors/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vendors-verify': RouteRecordInfo<
      'vendors-verify',
      '/vendors/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:path(.*)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/(authenticated)/authenticated.layout.vue': {
      routes:
        | 'dashboard'
        | 'settings-permissions'
        | 'settings-permissions-detail'
        | 'settings-roles'
        | 'settings-roles-create'
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
        | 'settings-roles-edit'
        | 'settings-users'
        | 'settings-users-create'
        | 'settings-users-detail'
        | 'settings-users-detail-role-assignments'
        | 'settings-users-edit'
        | 'vendors'
        | 'vendors-detail'
        | 'vendors-detail-bim'
        | 'vendors-detail-contacts'
        | 'vendors-detail-documents'
        | 'vendors-detail-reviews'
        | 'vendors-mine'
        | 'vendors-mine-bidang-usaha'
        | 'vendors-mine-contact-person'
        | 'vendors-mine-data-pendukung-keuangan'
        | 'vendors-mine-data-pendukung-legal'
        | 'vendors-mine-data-pendukung-teknis'
        | 'vendors-mine-input-bim'
        | 'vendors-mine-konfirmasi-selesai'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/dashboard/index.route.vue': {
      routes:
        | 'dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/permissions/index.route.vue': {
      routes:
        | 'settings-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/permissions/[permissionId]/detail.route.vue': {
      routes:
        | 'settings-permissions-detail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/index.route.vue': {
      routes:
        | 'settings-roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail.route.vue': {
      routes:
        | 'settings-roles-detail'
        | 'settings-roles-detail-permissions'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/detail/permissions/index.route.vue': {
      routes:
        | 'settings-roles-detail-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/[roleId]/edit.route.vue': {
      routes:
        | 'settings-roles-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/roles/create.route.vue': {
      routes:
        | 'settings-roles-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/index.route.vue': {
      routes:
        | 'settings-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail.route.vue': {
      routes:
        | 'settings-users-detail'
        | 'settings-users-detail-role-assignments'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/detail/role-assignments/index.route.vue': {
      routes:
        | 'settings-users-detail-role-assignments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/[userId]/edit.route.vue': {
      routes:
        | 'settings-users-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/settings/users/create.route.vue': {
      routes:
        | 'settings-users-create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/vendor.layout.vue': {
      routes:
        | 'vendors'
        | 'vendors-detail'
        | 'vendors-detail-bim'
        | 'vendors-detail-contacts'
        | 'vendors-detail-documents'
        | 'vendors-detail-reviews'
        | 'vendors-mine'
        | 'vendors-mine-bidang-usaha'
        | 'vendors-mine-contact-person'
        | 'vendors-mine-data-pendukung-keuangan'
        | 'vendors-mine-data-pendukung-legal'
        | 'vendors-mine-data-pendukung-teknis'
        | 'vendors-mine-input-bim'
        | 'vendors-mine-konfirmasi-selesai'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/index.route.vue': {
      routes:
        | 'vendors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/[vendorId]/detail.route.vue': {
      routes:
        | 'vendors-detail'
        | 'vendors-detail-bim'
        | 'vendors-detail-contacts'
        | 'vendors-detail-documents'
        | 'vendors-detail-reviews'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/[vendorId]/detail/bim/index.route.vue': {
      routes:
        | 'vendors-detail-bim'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/[vendorId]/detail/contacts/index.route.vue': {
      routes:
        | 'vendors-detail-contacts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/[vendorId]/detail/documents/index.route.vue': {
      routes:
        | 'vendors-detail-documents'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/[vendorId]/detail/reviews/index.route.vue': {
      routes:
        | 'vendors-detail-reviews'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/index.route.vue': {
      routes:
        | 'vendors-mine'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/bidang-usaha/index.route.vue': {
      routes:
        | 'vendors-mine-bidang-usaha'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/contact-person/index.route.vue': {
      routes:
        | 'vendors-mine-contact-person'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/data-pendukung-keuangan/index.route.vue': {
      routes:
        | 'vendors-mine-data-pendukung-keuangan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/data-pendukung-legal/index.route.vue': {
      routes:
        | 'vendors-mine-data-pendukung-legal'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/data-pendukung-teknis/index.route.vue': {
      routes:
        | 'vendors-mine-data-pendukung-teknis'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/input-bim/index.route.vue': {
      routes:
        | 'vendors-mine-input-bim'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(authenticated)/vendors/mine/konfirmasi-selesai/index.route.vue': {
      routes:
        | 'vendors-mine-konfirmasi-selesai'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/public.layout.vue': {
      routes:
        | 'auth-login'
        | 'vendors-register'
        | 'vendors-verify'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/(public)/auth/login/index.route.vue': {
      routes:
        | 'auth-login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/vendors/register/index.route.vue': {
      routes:
        | 'vendors-register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/(public)/vendors/verify/index.route.vue': {
      routes:
        | 'vendors-verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/not-found.route.vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
